<?php

INSERT INTO `personas` (`nombre`,`apellido`,`mail`,`id_rol`,`id_pais`) VALUES 
('LUIS RODOLFO' ,'LARA', 'verificar_mail@mail.com','1','1'),
('RODOLFO RAMÓN ' ,'RIZO', 'verificar_mail@mail.com','1','1'),
('CLAUDIO ALEJANDRO' ,' ARIZA', 'verificar_mail@mail.com','1','1'),
('VILMA DALILA' ,' VARAS', 'verificar_mail@mail.com','1','1'),
('ANDREA LEONOR' ,'AGUERO', 'verificar_mail@mail.com','1','1'),
('CRISTINA SUSANA' ,'GRAMAJO', 'verificar_mail@mail.com','1','1'),
('MARCELO FABIO' ,'ROLDAN', 'verificar_mail@mail.com','1','1'),
('VANESA' ,'GALLARDO', 'verificar_mail@mail.com','1','1'),
('CAMILLE ' ,'GRINGS SILVA', 'verificar_mail@mail.com','1','1'),
('DÉBORA' ,'NICE FERREIRA BARBOSA', 'verificar_mail@mail.com','1','1'),
('LEANDRO' ,'G. RASCH', 'verificar_mail@mail.com','1','1'),
('SANDRA TERESINHA' ,'MIORELLI', 'verificar_mail@mail.com','1','1'),
('AMERICO' ,'SIRVENTE', 'verificar_mail@mail.com','1','1'),
('ELISA' ,'OLIVA', 'verificar_mail@mail.com','1','1'),
('MARIA INES' ,'CIANCIO', 'verificar_mail@mail.com','1','1'),
('LUCY' ,'RIOS', 'verificar_mail@mail.com','1','1'),
('MARTA' ,'ORPI', 'verificar_mail@mail.com','1','1'),
('MABEL' ,'SOSA', 'verificar_mail@mail.com','1','1'),
('MARÍA LUISA' ,'BOSSOLASCO', 'verificar_mail@mail.com','1','1'),
('EUGENIA ELIZABETH' ,'ENRICO', 'verificar_mail@mail.com','1','1'),
('BEATRIZ ADRIANA' ,'CASANOVA', 'verificar_mail@mail.com','1','1'),
('ROXANA JUDITH' ,'ENRICO', 'verificar_mail@mail.com','1','1'),
('MILENA' ,'RAMÍREZ BAUTISTA', 'verificar_mail@mail.com','1','1'),
('MARÍA VICTORIA' ,'MURCIA ARREGOCES', 'verificar_mail@mail.com','1','1'),
('FRANCISCO DANIEL' ,'MENDOZA VARGAS', 'verificar_mail@mail.com','1','1'),
('JUAN SEBASTIAN' ,'BUSTAMANTE MONTOYA', 'verificar_mail@mail.com','1','1'),
('CAROLINA' ,'MEJIA', 'verificar_mail@mail.com','1','1'),
('JESSICA PAOLA' ,'OSORIO CABALLERO', 'verificar_mail@mail.com','1','1'),
('BASHIR YACUB' ,'BERMUDEZ', 'verificar_mail@mail.com','1','1'),
('SERGIO LUIS' ,'VARGAS MELENDEZ', 'verificar_mail@mail.com','1','1'),
('DAYANA ALEJANDRA' ,' BARRERA BUITRAGO', 'verificar_mail@mail.com','1','1'),
('DENISE CAROLINE' ,'ARGUELLES PABON', 'verificar_mail@mail.com','1','1'),
('ALEJANDRA' ,'ROA', 'verificar_mail@mail.com','1','1'),
('ANYIN' ,'MARTINEZ', 'verificar_mail@mail.com','1','1'),
('GERALDINE' ,'ISAZA', 'verificar_mail@mail.com','1','1'),
('DANIEL' ,'BEJARANO', 'verificar_mail@mail.com','1','1'),
('PEDRO' ,'MEDINA', 'verificar_mail@mail.com','1','1'),
('LUIS' ,'GAMA', 'verificar_mail@mail.com','1','1'),
('MÓNICA' ,'AGUDELO', 'verificar_mail@mail.com','1','1'),
('LORENA' ,'CASTAÑO', 'verificar_mail@mail.com','1','1'),
('CAROLINA' ,'MEJÍA', 'verificar_mail@mail.com','1','1'),
('CRISTIAN CAMILO' ,'PORTILLO', 'verificar_mail@mail.com','1','1'),
('JOHAN' ,'NAVARRO', 'verificar_mail@mail.com','1','1'),
('ELENA BEATRIZ ' ,'DURÁN', 'verificar_mail@mail.com','1','1'),
('SILVINA ISABEL' ,'UNZAGA', 'verificar_mail@mail.com','1','1'),
('MARGARITA MARÍA' ,'ALVAREZ', 'verificar_mail@mail.com','1','1'),
('PABLO SEBASTIÁN' ,'FANTINI', 'verificar_mail@mail.com','1','1'),
('MIRIAM' ,'BIDYERAN', 'verificar_mail@mail.com','1','1'),
('MARCELA' ,'TORRES', 'verificar_mail@mail.com','1','1'),
('DIANA JANETH' ,'LANCHEROS-CUESTA', 'verificar_mail@mail.com','1','1'),
('CARLOS' ,'BERNAL GRANADOS', 'verificar_mail@mail.com','1','1'),
('MAGLE' ,'SANCHEZ', 'verificar_mail@mail.com','1','1'),
('LAURA' ,'MANCERA', 'verificar_mail@mail.com','1','1'),
('SILVIA' ,'BALDIRIS', 'verificar_mail@mail.com','1','1'),
('ANGEL RUBÉN' ,'BARBERIS', 'verificar_mail@mail.com','1','1'),
('LORENA ELIZABETH' ,'DEL MORAL SACHETTI', 'verificar_mail@mail.com','1','1'),
('ANYELA LORENA' ,'OROZCO MORENO', 'verificar_mail@mail.com','1','1'),
('VALENTINA' ,'TABARES MORALES', 'verificar_mail@mail.com','1','1'),
('NÉSTOR DARIO' ,'DUQUE MÉNDEZ', 'verificar_mail@mail.com','1','1'),
('DIANA VANESSA' ,'SÁNCHEZ MORALES', 'verificar_mail@mail.com','1','1'),
('LUIS FELIPE' ,'LONDOÑO ROJAS', 'verificar_mail@mail.com','1','1'),
('MARIA ALEJANDRA' ,'HURTADO PARRA', 'verificar_mail@mail.com','1','1'),
('CRISTINA' ,'RIVERA', 'verificar_mail@mail.com','1','1'),
('JULIA' ,'PINEDA', 'verificar_mail@mail.com','1','1'),
('JAVIER' ,'LOPEZ', 'verificar_mail@mail.com','1','1'),
('MARIA VICTORIA' ,'HERNANDEZ VARGAS', 'verificar_mail@mail.com','1','1'),
('RAUL' ,'ANCIZAR MUNEVAR MOLINA', 'verificar_mail@mail.com','1','1'),
('GLORIA' ,'SIERRA', 'verificar_mail@mail.com','1','1'),
('MARIA LUISA' ,'ALVAREZ MEJÍA', 'verificar_mail@mail.com','1','1')


?>